- hosts: localhost
  connection: local
  become: true

#  pre_tasks:
#    - name: update repositories
#      apt:
#        update_cache: yes
#        force_apt_get: yes
#      changed_when: False

  tasks:
    -  include_tasks: configuration/users.yml
       state: latest
    -  include_tasks: tasks/cron.yml
       state: latest
    -  include_tasks: configuration/initial_config.yml
       state: latest
    -  include_tasks: tasks/update.yml
       state: latest
    -  include_tasks: configuration/ufw.yaml
       state: latest
