- hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: update repositories
      apt:
        update_cache: yes
      changed_when: False

  tasks:
    -  include_tasks: configuration/users.yml
    -  include_tasks: tasks/cron.yml
    -  include_tasks: configuration/initial_config.yml
    -  include_tasks: tasks/update.yml