- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "Sensor Configuration"
    minute: "10"
    job: "sudo ansible-pull -C lab -o -U https://github.com/unsinc/uns-sensor.git >/dev/null 2>&1 | logger -t Sensor Configuration Validation"

- name: Start Sricata
  cron: 
    user: docker
    name: Starting Suricata
    special_time: reboot
    job: "sleep 120 && docker exec IDS /bin/bash -c 'service suricata start' >/dev/null 2>&1 | logger -t Starting Suricata"
    state: absent

- name: Start Sricata
  cron: 
    user: docker
    name: Starting Suricata
    special_time: reboot
    job: "sleep 120 && docker exec IDS /bin/bash -c 'service suricata start' >/dev/null 2>&1 | logger -t Sensor Starting Suricata"

- name: Update the Surcata Rule Sources
  cron:
    user: ansible
    name: "Suricata Rule Update"
    hour: "12"
    job: "sudo suricata-update --suricata-version 7.0.3 update-sources >> /var/log/suricata/suricata_update.log >/dev/null 2>&1 | logger -t Suricata Rules Update"
    state: absent

- name: Update the Surcata Rule Sources
  cron:
    user: ansible
    name: "Suricata Rule Sources Update"
    hour: "12"
    job: "sudo suricata-update --suricata-version 7.0.3 update-sources >> /var/log/suricata/suricata_update.log >/dev/null 2>&1 | logger -t Suricata Rule Sources Update"

- name: Update the Suricata Rules
  cron:
    user: ansible
    name: "Suricata Rule Update"
    minute: "5"
    hour: "12"
    job: "sudo suricata-update --suricata-version 7.0.3 >> /var/log/suricata/suricata_update.log >/dev/null 2>&1 | logger -t Suricata Rules Update"

- name: Migrate the suricata rules to the suricata directory
  cron:
    user: docker
    name: "Moving the Suricata Rules to the suricata directory"
    minute: "30"
    hour: "12"
    job: "cp /var/lib/suricata/rules/ /sns/IDS/suricata/ >/dev/null 2>&1 | logger -t Suricata Updating the IDS Rules"

- name: Restart the Suricata Service to apply the new rules
  cron: 
    user: docker
    name: Suricata Restart
    minute: "45"
    hour: "12"
    job: "docker exec IDS /bin/bash -c 'service suricata restart' >/dev/null 2>&1 | logger -t Suricata Applying the most recent IDS Rules"

- name: Check that Sricata is running
  cron: 
    user: docker
    name: Checking that Suricata is running
    minute: "*/10"
    job: "bash /sns/docker/suricata_check.sh >/dev/null 2>&1 | logger -t Suricata Checking if service is running"

# Uncomment the section below in IDS Multi-Tenency
#- name: update the eth1 suricata rules
#  cron:
#    user: docker
#    name: "eth1 Suricata Rules Update"
#    minute: "30"
#    hour: "12"
#    job: "cp /var/lib/suricata/rules/ /Docker/IDS/suricata/eth1/ 2>&1 | logger -t Suricata Updating the eth1 Rules"
#
#- name: update the eth2 suricata rules
#  cron:
#    user: docker
#    name: "eth2 Suricata Rules Update"
#    minute: "30"
#    hour: "12"
#    job: "cp /var/lib/suricata/rules/ /Docker/IDS/suricata/eth2/ 2>&1 | logger -t Suricata Updating the eth2 Rules"
#
#- name: update the eth3 suricata rules
#  cron:
#    user: docker
#    name: "eth3 Suricata Rules Update"
#    minute: "30"
#    hour: "12"
#    job: "cp /var/lib/suricata/rules/ /Docker/IDS/suricata/eth3/ 2>&1 | logger -t Suricata Updating the eth3 Rules"
#
#- name: update the eth4 suricata rules
#  cron:
#    user: docker
#    name: "eth4 Suricata Rules Update"
#    minute: "30"
#    hour: "12"
#    job: "cp /var/lib/suricata/rules/ /Docker/IDS/suricata/eth4/ 2>&1 | logger -t Suricata Updating the eth4 Rules"
#
#- name: update the eth5 suricata rules
#  cron:
#    user: docker
#    name: "eth5 Suricata Rules Update"
#    minurte: "30"
#    hour: "12"
#    job: "cp /var/lib/suricata/rules/ /Docker/IDS/suricata/eth5/ 2>&1 | logger -t Suricata Updating the eth5 Rules"
