- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "Sensor Configuration"
    minute: "*/10"
    job: "/usr/bin/ansible-pull -o -U https://github.com/unsinc/sensor.git 2>&1 | logger -t Sensor_Configuration"
