- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "Sensor Configuration"
    minute: "10"
    job: "sudo ansible-pull -U https://github.com/unsinc/uns-sensor.git 2>&1 | logger -t Sensor Configuration Validation"

- name: Start Sricata
  cron: 
    user: docker
    name: Starting Suricata
    special_time: reboot
    job: "sleep 300 && docker exec -it IDS /bin/bash service suricata start 2>&1 | logger -t Starting Suricata"

- name: update the suricata rules
  cron:
    user: suricata
    name: "Suricata Rule Update"
    hour: "12"
    job: "suricata-update >> /var/log/suricata/suricata_update.log 2>&1 | logger -t Suricata Rules Update"

- name: Migrate the suricata rules to the suricata directory
  cron:
    user: docker
    name: "Moving the Suricata Rules to the suricata directory"
    minute: "30"
    hour: "12"
    job: "cp /var/lib/suricata/rules/ /sns/IDS/suricata/ 2>&1 | logger -t Suricata Updating the IDS Rules"

- name: Restart the Suricata Service to apply the new rules
  cron: 
    user: docker
    name: Suricata Restart
    minute: "45"
    hour: "12"
    job: "docker exec -it IDS /bin/bash service suricata restart 2>&1 | logger -t Suricata Applying the most recent IDS Rules"

# Uncomment the section below in IDS Multi-Tenency
#- name: update the eth1 suricata rules
#  cron:
#    user: docker
#    name: "eth1 Suricata Rules Update"
#    minute: "30"
#    hour: "12"
#    job: "cp /var/lib/suricata/rules/ /Docker/IDS/suricata/eth1/ 2>&1 | logger -t Suricata Updating the eth1 Rules"
#
#- name: update the eth2 suricata rules
#  cron:
#    user: docker
#    name: "eth2 Suricata Rules Update"
#    minute: "30"
#    hour: "12"
#    job: "cp /var/lib/suricata/rules/ /Docker/IDS/suricata/eth2/ 2>&1 | logger -t Suricata Updating the eth2 Rules"
#
#- name: update the eth3 suricata rules
#  cron:
#    user: docker
#    name: "eth3 Suricata Rules Update"
#    minute: "30"
#    hour: "12"
#    job: "cp /var/lib/suricata/rules/ /Docker/IDS/suricata/eth3/ 2>&1 | logger -t Suricata Updating the eth3 Rules"
#
#- name: update the eth4 suricata rules
#  cron:
#    user: docker
#    name: "eth4 Suricata Rules Update"
#    minute: "30"
#    hour: "12"
#    job: "cp /var/lib/suricata/rules/ /Docker/IDS/suricata/eth4/ 2>&1 | logger -t Suricata Updating the eth4 Rules"
#
#- name: update the eth5 suricata rules
#  cron:
#    user: docker
#    name: "eth5 Suricata Rules Update"
#    minurte: "30"
#    hour: "12"
#    job: "cp /var/lib/suricata/rules/ /Docker/IDS/suricata/eth5/ 2>&1 | logger -t Suricata Updating the eth5 Rules"
