- name: install cron job (ansible-pull)
  cron:
    user: ansible
    name: "Sensor Configuration"
    minute: "10"
    job: "/usr/bin/ansible-pull -U https://github.com/unsinc/uns-sensor.git 2>&1 | logger -t Sensor Configuration"

- name: update the suricata rules
  cron:
    user: suricata
    name: "Suricata Rule Update"
    hour: "12"
    job: "suricata-update | logger -t Suricata Rules Update"

- name: Migrate the suricata rules to the suricata directory
  cron:
    user: docker
    name: "Moving the Suricata Rules to the suricata directory"
    minute: "30"
    hour: "12"
    job: "cp /var/lib/suricata/rules/ /Docker/IDS/suricata/ | logger -t Suricata Updating the IDS Rules"

- name: Restart the Suricata Service to apply the new rules
  cron: 
    user: docker
    name: Suricata Restart
    minute: "45"
    hour: "12"
    job: "sudo docker exec -it IDS /bin/bash service suricata restart | logger -t Suricata Applying the most recent IDS Rules"

# Uncomment the section below in IDS Multi-Tenency
#- name: update the eth1 suricata rules
#  cron:
#    user: docker
#    name: "eth1 Suricata Rules Update"
#    minute: "30"
#    hour: "12"
#    job: "cp /var/lib/suricata/rules/ /Docker/IDS/suricata/eth1/ | logger -t Suricata Updating the eth1 Rules"
#
#- name: update the eth2 suricata rules
#  cron:
#    user: docker
#    name: "eth2 Suricata Rules Update"
#    minute: "30"
#    hour: "12"
#    job: "cp /var/lib/suricata/rules/ /Docker/IDS/suricata/eth2/ | logger -t Suricata Updating the eth2 Rules"
#
#- name: update the eth3 suricata rules
#  cron:
#    user: docker
#    name: "eth3 Suricata Rules Update"
#    minute: "30"
#    hour: "12"
#    job: "cp /var/lib/suricata/rules/ /Docker/IDS/suricata/eth3/ | logger -t Suricata Updating the eth3 Rules"
#
#- name: update the eth4 suricata rules
#  cron:
#    user: docker
#    name: "eth4 Suricata Rules Update"
#    minute: "30"
#    hour: "12"
#    job: "cp /var/lib/suricata/rules/ /Docker/IDS/suricata/eth4/ | logger -t Suricata Updating the eth4 Rules"
#
#- name: update the eth5 suricata rules
#  cron:
#    user: docker
#    name: "eth5 Suricata Rules Update"
#    minurte: "30"
#    hour: "12"
#    job: "cp /var/lib/suricata/rules/ /Docker/IDS/suricata/eth5/ | logger -t Suricata Updating the eth5 Rules"
