- name: "Get Suricata PID"
  shell: >
    echo -n
    $(pgrep suricata)
  register: suricata_procs

- name: "Checking is Suricata is running and starting the Suricata process if it has stopped"
  shell: 
    cmd: sudo docker exec IDS /bin/bash -c "service suricata start"
  when:
    - suricata_procs.stat.exists|bool == false