- name: Update apt-get repo and cache in the sensor
  apt: 
    update_cache: yes 
    force_apt_get: yes  
    cache_valid_time: 3600

- name: Upgrade all packages used by the sensor
  shell: 
    cmd: |
        sudo apt-get -s dist-upgrade | grep "^Inst" | grep -i securi | awk -F " " {'print $2'} | xargs sudo apt-get install -y

- name: Check if a reboot is needed for the sensor
  register: reboot_required_file
  stat: 
    path: /var/run/reboot-required 
    get_md5: false
  
- name: Reboot box if kernel/libs updated and requested by the system
  shell: "sleep 10 && /sbin/shutdown -r 08:00 'Reboot initiated by Ansible to update system libs/kernel as needed'"
  args:
    removes: /var/run/reboot-required
  async: 300
  poll: 0
  ignore_errors: true
  when: reboot_required_file.stat.exists == true
