# Dockerfile to build a Suricata docker container

# Set the base image to Ubuntu
FROM ubuntu:22.04

# File Author
MAINTAINER unsinc

# Update the repos
RUN apt update

# Add the Suricata repository
RUN add-apt-repository -y ppa:oisf/suricata-stable

# Update the repos and install Suricata
RUN apt update && apt install -y suricata

# Copy the suricata config to its config location
ADD /Docker/IDS/suricata/suricata.yaml  /etc/suricata/suricata.yaml
ADD /Docker/IDS/suricata/eth1/eth1.yaml /etc/suricata/eth1/eth1.yaml
ADD /Docker/IDS/suricata/eth1/eth2.yaml /etc/suricata/eth1/eth2.yaml
ADD /Docker/IDS/suricata/eth1/eth3.yaml /etc/suricata/eth1/eth3.yaml
ADD /Docker/IDS/suricata/eth1/eth4.yaml /etc/suricata/eth1/eth4.yaml
ADD /Docker/IDS/suricata/eth1/eth5.yaml /etc/suricata/eth1/eth5.yaml
ADD /Docker/IDS/suricata/eth2/classification.config 

# Start the Suricata/Filebeat service when the container is started
CMD service suricata start 