services:
  IDS:
    image: suricata
    hostname: IDS
    container_name: IDS
    build:
      context: ./Docker
      dockerfile: dockerfile
    restart: unless-stopped
    volumes:
      - /var/log/suricata:/var/log/suricata