# Dockerfile to build a Suricata docker container

# Set the base image to Ubuntu
FROM ubuntu:22.04

# File Author
MAINTAINER unsinc

# Update the repos
RUN apt update

# Allows us to add repositories and rum some commands
RUN apt install -y software-properties-common wget apt-transport-https net-tools

# Add the Suricata repository
RUN add-apt-repository -y ppa:oisf/suricata-stable

# Update the repos and install Suricata
RUN apt update && apt install -y suricata && apt install net-tools

#Start the Suricata/Filebeat service when the container is started
CMD echo 'Hello World'; sleep infinity
CMD service suricata start