version: '3.7'
services:
  IDS:
    image: suricata
    hostname: IDS
    container_name: IDS
    cap_add:
        - NET_ADMIN
    build:
      context: /sns/docker
      dockerfile: dockerfile
    restart: always
    volumes:
      - /var/log/suricata:/var/log/suricata
      - /sns/IDS/suricata:/etc/suricata
    command: sudo iptables -I FORWARD -i eth1 -j NFQUEUE && sudo iptables -I FORWARD -i eth2 -j NFQUEUE && sudo iptables -I FORWARD -i eth3 -j NFQUEUE && sudo iptables -I FORWARD -i eth4 -j NFQUEUE && sudo iptables -I FORWARD -i eth5 -j NFQUEUE