services:
  myubuntu:
    hostname: IDS
    image: ubuntu:22.04
    container_name: IDS
    restart: always
    volumes:
      - 'suricata-log:/var/log/suricata/'
     # - '/Docker/IDS/suricata/eth1:/var/lib/suricata/eth1'
     # - '/Docker/IDS/suricata/eth2:/var/lib/suricata/eth2'
     # - '/Docker/IDS/suricata/eth3:/var/lib/suricata/eth3'
     # - '/Docker/IDS/suricata/eth4:/var/lib/suricata/eth4'
     # - '/Docker/IDS/suricata/eth5:/var/lib/suricata/eth5'

volumes:
  suricata-log:
    external: true
      name: /var/log/suricata/