# Dockerfile to build a Suricata docker container

# Set the base image to Ubuntu
FROM ubuntu:22.04

# File Author
MAINTAINER unsinc

# Update the repos
RUN apt update

# Allows us to add repositories and rum some commands
RUN apt install -y software-properties-common wget apt-transport-https net-tools

# Add the Suricata repository
RUN add-apt-repository -y ppa:oisf/suricata-stable

# Update the repos and install Suricata
RUN apt update && apt install -y suricata net-tools iptables

# Add the iptables rules for suricata
RUN iptables -I FORWARD -i eth1 -j NFQUEUE && iptables -I FORWARD -i eth2 -j NFQUEUE && iptables -I FORWARD -i eth3 -j NFQUEUE && iptables -I FORWARD -i eth4 -j NFQUEUE && iptables -I FORWARD -i eth5 -j NFQUEUE 

#Start the container
CMD tail -F /dev/null