services:
  IDS:
    image: suricata
    hostname: IDS
    container_name: IDS
    build:
      context: /Docker
      dockerfile: dockerfile
    restart: always
    volumes:
      - /var/log/suricata:/var/log/suricata
      - /Docker/IDS/suricata/suricata.yaml:/etc/suricata/suricata.yaml
      - /Docker/IDS/suricata:/etc/suricata