- name: Prep for the docker environment
  apt:
    name:
      - ca-certificates
      - gnupg

- name: Update the APT repository
  apt:
    update_cache: yes
    force_apt_get: yes
  changed_when: False

- name: Add Docker GPG apt Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add repository into sources list
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
    state: present
    filename: docker

- name: Initial Sensor Configuration
  apt:
    name:  
      - auditd
      - htop
      - nano
      - psmisc
      - net-tools
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
      - python3-pip
    
- name: Create a logical volume sns with the rest of the available space
  lvol:
    vg: ubuntu-vg
    lv: sns
    size: 100%FREE
  ignore_errors: true

- name: Create /sns directory
  file:
    path: /sns
    state: directory
    mode: '0755'

- name: Create xfs filesystem on ubuntu--vg-sns
  filesystem:
    fstype: ext4
    dev: /dev/mapper/ubuntu--vg-sns

- name: Mount sns volume
  mount:
    path: /sns
    src: /dev/mapper/ubuntu--vg-sns
    fstype: ext4
    boot: true
    state: mounted

- name: Collect the highest 5 interface names on the sensor
  shell: "ansible localhost -m setup -a filter=ansible_interfaces | sort | grep -e ens -e enp | tail -5 | sed 's/ //g' | sed 's/\"//g' | sed 's/,//g' > /home/uns/span_interfaces.txt"

- name: Set all monitoring interfaces to optional
  shell: "netplan set ethernets.{{ item }}.optional=true"
  loop: "{{ lookup('file', '/home/uns/span_interfaces.txt').splitlines() }}"

- name: Dsiable DHCP on the SPAN interfaces
  shell: "netplan set ethernets.{{ item }}.dhcp4=false"
  loop: "{{ lookup('file', '/home/uns/span_interfaces.txt').splitlines() }}"