- name: Prep for the docker environment
  apt:
    name:
      - ca-certificates
      - gnupg

- name: Install the keyrings
  shell: "install -m 0755 -d /etc/apt/keyrings"

- name: Add the needed keys
  block:
    - name: dockerrepo | no apt key 
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg 
        dest: /etc/apt/keyrings/docker.gpg

    - name: dockerrepo | apt source
      apt_repository:
        repo: "deb [{{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
 
- name: Update the APT repository
  apt:
    update_cache: yes
  changed_when: False

- name: Initial Sensor Configuration
  apt:
    name:  
      - auditd
      - htop
      - nano
      - psmisc
      - net-tools
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Upgrade all packages used by the sensor
  apt: upgrade=dist force_apt_get=yes

- name: Set all monitoring interfaces to optional
  shell: "netplan set ethernets.enp3s0.optional=true && \
    netplan set ethernets.enp4s0f0.optional=true && \
    netplan set ethernets.enp4s0f1.optional=true && \
    netplan set ethernets.enp5s0.optional=true && \
    netplan set ethernets.enp6s0.optional=true && \
    netplan set ethernets.ens33.optional=true && \
    netplan set ethernets.ens34.optional=true && \
    netplan set ethernets.ens35.optional=true && \
    netplan set ethernets.ens36.optional=true && \
    netplan set ethernets.ens37.optional=true"

- name: Copy the docker-compose file to the Docker directory
  copy:
    src: ~/.ansible/pull/uns-sensor-01/configuration/docker-compose.yml
    dest: /Docker

- name: Install the IDS container
  community.docker.docker_compose:
    project_src: /Docker/docker-compose.yml