- name: Prep for the docker environment
  apt:
    name:
      - ca-certificates
      - gnupg

- name: Install the keyrings
  shell: "install -m 0755 -d /etc/apt/keyrings"

- name: Add the needed keys
  block:
    - name: dockerrepo | no apt key 
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg 
        dest: /etc/apt/keyrings/docker.gpg

    - name: dockerrepo | apt source
      apt_repository:
        repo: "deb [arch={{ ansible_userspace_architecture }} signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
 
- name: Update the APT repository
  apt:
    update_cache: yes
  changed_when: False

- name: Initial Sensor Configuration
  apt:
    name:  
      - auditd
      - htop
      - nano
      - psmisc
      - net-tools
      - python2-minimal
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin

- name: Upgrade all packages used by the sensor
  apt: upgrade=dist force_apt_get=yes

- name: Set all monitoring interfaces to optional
  shell: "netplan set ethernets.enp3s0.optional=true && \
    netplan set ethernets.enp4s0f0.optional=true && \
    netplan set ethernets.enp4s0f1.optional=true && \
    netplan set ethernets.enp5s0.optional=true && \
    netplan set ethernets.enp6s0.optional=true && \
    netplan set ethernets.ens33.optional=true && \
    netplan set ethernets.ens34.optional=true && \
    netplan set ethernets.ens35.optional=true && \
    netplan set ethernets.ens36.optional=true && \
    netplan set ethernets.ens37.optional=true"

- name: Copy the docker-compose file to the Docker directory
  copy:
    src: ~/.ansible/pull/uns-sensor-01/configuration/docker-compose.yml
    dest: /Docker

#- name: Install the IDS container
#  community.docker.docker_compose:
#    vars:
#      ansible_python_interpreter: /usr/bin/python3
#    project_src: /Docker/docker-compose.yml

- name: Create Docker span networks
  shell: "docker network create -d macvlan -o macvlan_mode=passthru -o parent=enp3s0 eth1_span"
#    docker network create -d macvlan -o macvlan_mode=passthru -o parent=enp5s0 eth2_span && \
#    docker network create -d macvlan -o macvlan_mode=passthru -o parent=enp6s0 seth3_span && \
#    docker network create -d macvlan -o macvlan_mode=passthru -o parent=enp4s0f0 sfp+1_span && \
#    docker network create -d macvlan -o macvlan_mode=passthru -o parent=enp4s0f1 sfp+2_span && \
#    docker network create -d macvlan -o macvlan_mode=passthru -o parent=ens33 ens33_span && \
#    docker network create -d macvlan -o macvlan_mode=passthru -o parent=ens34 ens34_span && \
#    docker network create -d macvlan -o macvlan_mode=passthru -o parent=ens35 ens35_span && \
#    docker network create -d macvlan -o macvlan_mode=passthru -o parent=ens36 ens36_span && \
#    docker network create -d macvlan -o macvlan_mode=passthru -o parent=ens37 ens37_span"

- name: Install the IDS container with Docker Compose 
  shell: docker compose -f /Docker/docker-compose.yml up -d
