- name: Initial Sensor Configuration
  apt:
    name:  
      - auditd
      - htop
      - nano
      - psmisc
      - net-tools

- name: Upgrade all packages used by the sensor
  apt: upgrade=dist force_apt_get=yes

- name: Set all monitoring interfaces to optional
  shell: "netplan set ethernets.enp3s0.optional=true && \
    netplan set ethernets.enp4s0f0.optional=true && \
    netplan set ethernets.enp4s0f1.optional=true && \
    netplan set ethernets.enp5s0.optional=true && \
    netplan set ethernets.enp6s0.optional=true && \
    netplan set ethernets.ens33.optional=true && \
    netplan set ethernets.ens34.optional=true && \
    netplan set ethernets.ens35.optional=true && \
    netplan set ethernets.ens36.optional=true && \
    netplan set ethernets.ens37.optional=true"

- name: Copy the docker-compose file to the Docker directory
  copy:
    src: ~/.ansible/pull/uns-sensor-01/configuration/docker-compose.yml
    dst: /Docker

- name: Install the IDS container
  community.docker.docker_compose:
    project_src: ~/.ansible/pull/uns-sensor-01/configuration/docker-compose.yml