- name: Initial Sensor Configuration
  apt:
    name:  
      - auditd
      - htop
      - nano
      - psmisc
      - net-tools

- name: Upgrade all packages used by the sensor
  apt: upgrade=dist force_apt_get=yes